name: Python Scripts CI

on:
  schedule:
    # Run on the 1st day of every month at 00:00 UTC
    - cron: '0 0 1 * *'
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch: # Allow manual trigger


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # You can test your matrix by printing the current Python version
      - name: Run Scrapers
        run: python scraper.py
      - uses: actions/upload-artifact@v4
        with:
          name: hop_database
          path: |
            data/yakimachiefhops.json
            data/baathhaas.json
            data/hopsteiner.json
            data/combined.json
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate version tag
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "schedule" || "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            # Generate version based on current date (YYYY.MM format)
            VERSION="v$(date +'%Y.%m')"
            echo "tag_name=$VERSION" >> $GITHUB_OUTPUT
            echo "release_name=Monthly Release $VERSION" >> $GITHUB_OUTPUT
          else
            # Use the pushed tag
            echo "tag_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
            echo "release_name=Release ${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi
      
      - name: Create and push tag (for scheduled runs)
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag ${{ steps.version.outputs.tag_name }}
          git push origin ${{ steps.version.outputs.tag_name }}
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.tag_name }}
          release_name: ${{ steps.version.outputs.release_name }}
          draft: false
          prerelease: false
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: hop_database
          path: ./data

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./data/combined.json
          asset_name: combined.json
          asset_content_type: application/json